### ISSUE TITLE
Set up automated releases

### ISSUE THREAD

**Issue by RyanClementsHax** [mantis-apps/mantis-cli#33]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Releases to npm are done manually as of now. This opens the door for human error during deployments. This could take the form of publishing the wrong thing, not publishing at all, or publishing the wrong version number.

Not automating this also requires more effort on maintainers to publish new versions manually.

### Describe the solution you'd like

This repo should have an automated release pipeline that generates release notes and new version based off of commit messages, creates github releases, and publishes to npm.

Commit message format should also be enforced through automation.

### What is the motivation / use case for changing the behavior?

This avoids human error in deployments and allows us to spend time on higher value tasks.

**Comment by orbitturner** [comment]
Hey Rayan if you want we can discuss this. 

We can use Actions for this.

**Comment by RyanClementsHax** [comment]
I agree that actions are a good fit for this.

I was thinking of using a similar setup to what I have for [tailwindcss-themer](https://github.com/RyanClementsHax/tailwindcss-themer). I'd love your thoughts though.
